### ISSUE TITLE
load language error

### ISSUE THREAD

**Issue by ffxivvillein** [easly1989/ffxiv_act_dfassist#2] opened 2019-03-12 02:54 UTC
When I chosen Korean(한국어), got error.

`[11:47:13] <D: 임무 데이터를 처리하던 중 문제 발생: After parsing a value an unexpected character was encountered: t. Path 'instances.7.name', line 34, position 7.>`

Japanese also got error, but English and French is ok.

**Comment by easly1989** [comment] 2019-03-12 08:00
It seems like one of the character of the instance.7.name (Halatali) is unexpected.

I just checked the korean translation and it says "할라탈리 수련장" -> "Halatali Training Center".

Honestly I don't speak Korean or Japanese, so i mostly grab the translations online from other devs (or from the game data).

I made a pre-release with a possible fix (as i found something related on stackoverflow)
[you can download it here and give it a try](https://github.com/easly1989/ffxiv_act_dfassist/releases/download/1.3.13_pre/DFAssist_1.3.13_pre.zip)

if you still have the problem i'll need to check it with more calm.

So, let me know!

**Comment by Jaehyuk-Lee** [comment] 2019-03-12 09:25
I think you should use utf-8 for json files.
I have codes like this in DFAssist
```
<data name="Data_EN_US" type="System.Resources.ResXFileRef, System.Windows.Forms">

<value>..\resources\data\en-us.json;System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089;utf-8</value>

</data>

<data name="Localization_FR_FR" type="System.Resources.ResXFileRef, System.Windows.Forms">

<value>..\resources\localization\fr-fr.json;System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089;utf-8</value>

</data>

<data name="Localization_KO_KR" type="System.Resources.ResXFileRef, System.Windows.Forms">

<value>..\resources\localization\ko-kr.json;System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089;utf-8</value>

</data>

<data name="Data_JA_JP" type="System.Resources.ResXFileRef, System.Windows.Forms">

<value>..\resources\data\ja-jp.json;System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089;utf-8</value>

</data>

<data name="Localization_JA_JP" type="System.Resources.ResXFileRef, System.Windows.Forms">

<value>..\resources\localization\ja-jp.json;System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089;utf-8</value>

</data>

<data name="Data_FR_FR" type="System.Resources.ResXFileRef, System.Windows.Forms">

<value>..\resources\data\fr-fr.json;System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089;utf-8</value>

</data>

<data name="Data_KO_KR" type="System.Resources.ResXFileRef, System.Windows.Forms">

<value>..\resources\data\ko-kr.json;System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089;utf-8</value>

</data>

<data name="Localization_EN_US" type="System.Resources.ResXFileRef, System.Windows.Forms">

<value>..\resources\localization\en-us.json;System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089;utf-8</value>

</data>
``` 


edit: pre release version may fix it

**Comment by easly1989** [comment] 2019-03-12 09:38
@Jaehyuk-Lee thank you for the heads-up!

But yeah, I just searched around the web and found that the problem may be the encoding, so I tried to do a quick fix with the pre-release (:

Hopefully it will work,
At the moment I cannot try it (As I am at work and unable to use ACT), so i'm keeping this open until i get to try it (or as soon as @ffxivvillein or anyone else is able to tell me if it works!)

Anyway, thank you again 👍

**Comment by ffxivvillein** [comment] 2019-03-12 11:22
It is working very well, but...
I executed first ACT and next I added dfassist, It was working.

By the way, ACT added dfassist is executed, it is immediately gone from task. I can't execute ACT since.

**Comment by easly1989** [comment] 2019-03-12 11:26
I'm sorry but I don't get if the problem was solved or it just generated other problems to you ^^'

From what i can understand you are saying that now, after you add the DFAssist plugin to ACT you are not able to start ACT again?
(it is a really strange and unexpected behavior to be honest, but if it is the case i'll watch into it asap)

**Comment by ffxivvillein** [comment] 2019-03-12 11:30
Yes.
So, I changed dfassist folder's name, ACT is revived again.

**Comment by easly1989** [comment] 2019-03-12 11:31
I'll look into it and let you know!

**Comment by ffxivvillein** [comment] 2019-03-12 11:34
Thanks, It may be a conflict between plugins.

I am using below list.
FFXIV_ACT_Plugin.dll
OverlayPlugin.dll
ACT.TTSYukkury.dll
ACT.SpecialSpellTimer.dll
FFXIV_MemoryReader.dll

**Comment by easly1989** [comment] 2019-03-12 11:52
I've just tried adding DFassist in a clean ACT install (after FFXIV_ACT_PLUGIN)
it started ok.

Then i closed ACT and re-opened, and it all went smoothly.

It really seems that there is a problem with the other plugins (like when closing or adding and enabling another plugin after dfassist triggers something change...)

The reason why your ACT was not starting anymore is because of hte dangling ACT process.

I'll look into this issue asap

**Comment by easly1989** [comment] 2019-03-12 12:16
Just added a new release:
- https://github.com/easly1989/ffxiv_act_dfassist/releases/download/1.3.14/DFAssist.zip

tested and it should work just fine,
@ffxivvillein let me know (so that we can close this issue! :) )

**Comment by ffxivvillein** [comment] 2019-03-12 12:25
Really appreciate!

It has no a problem and it very works.

**Closed as completed** 2019-03-12 13:30 UTC
