### ISSUE TITLE
Display layout

### ISSUE THREAD

**Issue by mooondark** [easly1989/ffxiv_act_dfassist#48] opened 2019-11-22 11:41 UTC
Is it possible to move the fields so it does not overlap with titles (as you can see on the following picture ?)

![image](https://user-images.githubusercontent.com/40036185/69422955-4f15c800-0d25-11ea-8778-f85d4b954af3.png)

**Comment by easly1989** [comment] 2019-11-22 12:04
Yeah is something i wanted to work on from some time.
All the settings placements are hardcoded and "ui tested" for english, thus giving unexpected results with different string lengths.

I'll look into it asap, but as it is not a bug (meaning that all the functionalities of the plugin are still working, and the plugin itself is completelu usable), for the moment I'll give no ETA ^^'

**Comment by mooondark** [comment] 2019-11-22 12:06
Yeah for sure :)

**Comment by easly1989** [comment] 2019-11-26 12:17
2.2.7 should solve this issue,
closing

**Closed as completed by easly1989** 2019-11-26 12:17 UTC
Labels: enhancement
