### ISSUE TITLE
Version 1.5.0 ACT exception

### ISSUE THREAD

**Issue by Zaltenos** [easly1989/ffxiv_act_dfassist#10] opened 2019-07-26 22:53 UTC
This is likely related or similar to #9, however I do not use Triggernometry, regardless upon opening ACT an exception occurs and the process is killed off, reverting to 1.4.5 from 1.5.0 no longer kills ACT. 

My log is attached.
[Advanced Combat Tracker.log](https://github.com/easly1989/ffxiv_act_dfassist/files/3437574/Advanced.Combat.Tracker.log)

**Comment by easly1989** [comment] 2019-07-27 10:37
As I said on the related issue.
I was not able to reproduce your issue.

And I've installed and being using all this plugins 
![immagine](https://user-images.githubusercontent.com/3910202/61993337-a1422780-b06a-11e9-8794-053b1907b87d.png)

you may want to try and delete completely the DFAssist plugin folder and content
and download the latest release [here](https://github.com/easly1989/ffxiv_act_dfassist/releases/tag/1.5.1)

tell me if you keep experiencing the issue

**Comment by Zaltenos** [comment] 2019-07-27 12:04
I have completely deleted the old version files (1.4.5), and tried both 1.5.0 and 1.5.1, however the problem still remains, so whether it's a plugin conflict with other plugins or something specifically changed in the newer versions of this plugin.

It also does not matter if the game is running, or if it is closed.

![2019-07-27_13-03-49](https://user-images.githubusercontent.com/40673403/61994165-131c7000-b06f-11e9-81b1-7cddf38cf50d.png)
[Advanced Combat Tracker.log](https://github.com/easly1989/ffxiv_act_dfassist/files/3438136/Advanced.Combat.Tracker.log)

**Comment by easly1989** [comment] 2019-07-27 12:11
Uhm, I'll do more investigations as soon as I can
And report back!

**Comment by easly1989** [comment] 2019-07-28 08:50
Here I'm again.
So, it seems that for some reason your DFAssist is trying to "load" some settings that do not exist anymore in the new version. 
For instance it cannot find:

> _enableLoggingCheckBox

That control was removed in version 1.5.0, as Logging are always enabled by default.

The strange thing is that the code that handles the load of the settings is "crash-proof" (or at least it should be lol); and I tried adding and removing values to the config without reproducing your issue.

So, to clean completely your installation, and ensure no error occurs.
1. Download the [latest release](https://github.com/easly1989/ffxiv_act_dfassist/releases/latest) of the plugin
2. Wipe any trace of the plugin from the ACT plugins folder
3. Extract the latest DFAssist Plugin there
4. Delete the DFAssist.config.xml from **%AppData%\Advanced Combat Tracker\Config**
5. Try again launching ACT

In case you still have errors, please send again the log

**Comment by Zaltenos** [comment] 2019-07-28 11:02
That seems to have fixed the problem, working fine with version 1.5.4, thanks.

**Comment by Zaltenos** [comment] 2019-07-28 12:32
It would appear the issue still remains, deleting the old version files and old config files allowed it to work until I restarted ACT, then the same error happened again, alongside a new error window.

I also tested it with version 1.4.5 again which worked, and back to the latest version (1.5.4) which didn't.

So not sure if it's something that changed in the newer versions of this plugin, or somehow a plugin conflict is occurring.

[Advanced Combat Tracker.log](https://github.com/easly1989/ffxiv_act_dfassist/files/3439154/Advanced.Combat.Tracker.log)
![explorer_2019-07-28_13-26-30](https://user-images.githubusercontent.com/40673403/62006705-0fa2ea80-b13c-11e9-853f-d28f4c2c812f.png)

**Comment by easly1989** [comment] 2019-07-28 12:37
Very strange,
in this latest log there is no trace of a problem with DFAssist, it seems to be loaded without problems at all!

Removing the pluing will let ACT start normally, right?

**Comment by Zaltenos** [comment] 2019-07-28 12:40
Just tested, removing all traces of the plugin files and config files still allows ACT to work as normal.

**Comment by easly1989** [comment] 2019-07-28 12:46
Ok,
If you can, please install again only the latest version of the plugin.
And if you reproduce the problem, than send me the DFAssist config file that is in 
**%AppData%\Advanced Combat Tracker\Config**

so I can check what is going on there

**Comment by Zaltenos** [comment] 2019-07-28 12:58
I think I found the issue, it appears to be a plugin loading issue and/or conflict issue with Hojoring and its respective plugins, if DFAssist is above them ACT throws the error and crashes, if it's below then it works as expected. The load order as shown in the screenshot below works.

For whatever reason, version 1.5.0+ only has this, and not 1.4.5 or before, weird things.

![Advanced_Combat_Tracker_2019-07-28_13-56-40](https://user-images.githubusercontent.com/40673403/62006949-960cfb80-b13f-11e9-8bd4-cd9cbf34650b.png)

**Comment by easly1989** [comment] 2019-07-28 14:08
Found the problem, will be fixed in next release.
(It was a check on the calling plugin that wanted to load external libraries; it seems Hojoring uses some kind of information hiding, thus passing a nullreference to an event that normally has always a valure for the requestingplugin)

As soon as I publish the new release i'll link it here (and probably ask you to test it out and ensure that your problem is fixed)

Sorry for all the troubles,
Thanks for taking the time to write the issue and do all this tests :)
Have a nice game!

**Comment by easly1989** [comment] 2019-07-28 21:13
[Latest Release (1.5.5)](https://github.com/easly1989/ffxiv_act_dfassist/releases/latest)

Closing this, if you can (and want) to test it out for the issue you are free to do it
and in case you still find a way to repoduce the issue, feel free to reopen it ;)

Have a nice game :)

**Closed as completed by easly1989** 2019-07-28 21:13 UTC
